#!/usr/bin/env bash

set -o errexit
set -o pipefail

declare PROJECT_DIR="$1"                                                      
declare RESULTS_DIR="$2"/"$PROJECT_DIR"

rm -rf "$RESULTS_DIR"
mkdir -p "$RESULTS_DIR"

log_file=summarize-ignores-"$PROJECT_DIR".log
info_classes="$RESULTS_DIR"/ignored_classes.csv
info_methods="$RESULTS_DIR"/ignored_methods.csv

./parse-for-ignores "$PROJECT_DIR" 2>&1 | tee $log_file
echo "===================================================================="
grep "ALL IGNORED" $log_file> $info_classes
grep ^IGNORE $log_file > $info_methods
count=$(wc -l "$info_classes" | awk '{print $1}')
echo "Ignored classes count:$count. Written to: $info_classes"
count=$(wc -l "$info_methods" | awk '{print $1}')
echo "Ignored methods count: $count. Written to: $info_methods"
echo "Log file written to $log_file"

